stages:
  - build
  - deploy

variables:
  GCP_PROJECT_ID: gcp-vertexai-mlops-blueprint
  GCP_REGION: us-central1
  IMAGE_NAME: $GCP_REGION-docker.pkg.dev/$GCP_PROJECT_ID/mlops-repo/base-image
  DEPLOY_ONLY: false

build:
  stage: build
  image: docker:27.5.1
  services:
    - docker:27.5.1-dind
  variables:
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - apk add --no-cache jq curl
    - |
      ACCESS_TOKEN=$(curl -s -H "Metadata-Flavor: Google" "http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/token" | jq -r '.access_token')
    - echo $ACCESS_TOKEN | docker login -u oauth2accesstoken --password-stdin https://$GCP_REGION-docker.pkg.dev
  script:
    - docker build -t $IMAGE_NAME:$CI_COMMIT_SHORT_SHA .
    - docker push $IMAGE_NAME:$CI_COMMIT_SHORT_SHA
  rules:
    - if: $DEPLOY_ONLY == 'false' && ($CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH)


deploy:
  stage: deploy
  image: python:slim-bookworm
  before_script:
    - pip install kfp google-cloud-aiplatform google-cloud-pipeline-components
  script:
    - echo $IMAGE_NAME:$CI_COMMIT_SHORT_SHA
    - python3 main.py $IMAGE_NAME:$CI_COMMIT_SHORT_SHA
  rules:
    - if: $DEPLOY_ONLY == 'true'
    - if: ($CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH)