class BatchPredictionJobConfig:
    PROJECT_ID = 'gcp-vertexai-mlops-blueprint'
    LOCATION = 'asia-south1'
    BATCH_PREDICTION_JOB_NAME = 'TFT Batch Prediction'
    INPUT_URI = 'gs://batch-prediction-volume-forecasting/input/input.jsonl'
    OUTPUT_URI = 'gs://batch-prediction-volume-forecasting/output/'
    MODEL_RESOURCE_NAME = 'projects/848202130152/locations/asia-south1/models/9077488834081456128'
    DEPLOY_COMPUTE = 'n2-standard-2'
    REQUEST_FORMAT = 'jsonl'
    PREDICTIONS_FORMAT = 'jsonl'